AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  telegram-auto-clear-bot

  Sample SAM Template for telegram-auto-clear-bot

Resources:
  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: main/
      Handler: app.lambda_handler
      Runtime: python3.7
      Timeout: 30
      Events:
        Main:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: post
      Policies:
      - SSMParameterReadPolicy:
          ParameterName:
            "MessageAutoClearTelegramBotToken"
      - DynamoDBCrudPolicy:
          TableName:
            "telegram-auto-clear-bot-chats"

  SchedulerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: main/
      Handler: scheduler.lambda_handler
      Runtime: python3.7
      Timeout: 30
      Events:
        Scheduler:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            "telegram-auto-clear-bot-chats"
      - LambdaInvokePolicy:
          FunctionName:
            "telegram-auto-clear-bot-clear-message-worker"

  WorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "telegram-auto-clear-bot-clear-message-worker"
      CodeUri: main/
      Handler: clear_message_worker.lambda_handler
      Runtime: python3.7
      Timeout: 300
      MemorySize: 3008
      Policies:
      - SSMParameterReadPolicy:
          ParameterName:
            "MessageAutoClearTelegramBotToken"
      - DynamoDBCrudPolicy:
          TableName:
            "telegram-auto-clear-bot-chats"

  ChatTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: telegram-auto-clear-bot-chats
      PrimaryKey:
        Name: chat_id
        Type: String

Outputs:
  MainApi:
    Description: "API Gateway endpoint URL for Prod stage for main function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  MainFunction:
    Description: "Main Lambda Function ARN"
    Value: !GetAtt MainFunction.Arn
  MainFunctionIamRole:
    Description: "Implicit IAM Role created for main function"
    Value: !GetAtt MainFunctionRole.Arn
